# Automations
###############
- alias: Detect Motion
  trigger:
    - platform: state
      entity_id: sensor.living_room_thermostat_butterfly_operation_mode
      from: 'eco'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.rahul_ph
          state: 'not_home'
        - condition: state
          entity_id: device_tracker.ipad_rahul
          state: 'not_home'
        - condition: state
          entity_id: device_tracker.ipad_divya
          state: 'not_home'
        - condition: state
          entity_id: device_tracker.macbook_pro
          state: 'not_home'
        - condition: state
          entity_id: device_tracker.divya_ph
          state: 'not_home'
        - condition: state
          entity_id: sensor.samsung_tv
          state: 'off'
        - condition: state
          entity_id: sensor.chromecast
          state: 'off'
  action:
    - service: notify.rdpi
      data:
        title: 'Automation'
        message: Motion detected


###############
# Turn on corner light when nest switches from 
# away to home mode only when sun is down
- alias: We are home
  trigger:
    - platform: state
      entity_id: binary_sensor.nest_away_mode
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: switch.turn_on
      entity_id: switch.corner_light
    - service: notify.rdpi
      data:
        title: 'Automation'
        message: Run the automation for lights on with nest

###############
# Turn off firelight when corner light is turned on after 1min
- alias: Turn off firelight
  trigger: 
    - platform: state
      entity_id: switch.corner_light
      state: 'on'
      for: '00:01:00'
  condition:
    - condition: state
      entity_id: light.hall_light
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.hall_light

###############
# Send a push notification when login failure is logged
- alias: Login Failure
  hide_entity: true
  trigger:
    platform: template
    value_template: "{{ states('persistent_notification.httplogin') != 'unknown' }}"
  action:
    service: notify.rdpi
    data:
      title: 'Bad Login'
      message: There was a Hack attempt! Go Check HA GUI for details.

###############
# Notify when fan is on under away settings
- alias: Away Fan On
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_thermostat_butterfly_fan
      state: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.nest_away_mode
      state: 'on'
  action:
    - service: notify.rdpi
      data:
        title: 'Nest Mode'
        message: 'Fan ON under away mode'
        
###############
# Increase TV volume when aircon on
- alias: Increase TV volume
  trigger:
    - platform: state
      entity_id: sensor.living_room_thermostat_butterfly_hvac_state
      from: 'off'
      to: 'heating'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.samsung_tv
          state: 'On'
        - condition: state
          entity_id: media_player._un65ju6700_un65ju6700
          state: 'on'
        - condition: state
          entity_id: sensor.chromecast
          state: 'On'
        - condition: state
          entity_id: media_player.pastarun
          state: 'on'
  action:
    - service: script.volume_increase
      
###############
# Decrease TV volume when aircon off
- alias: Decrease TV volume
  trigger:
    - platform: state
      entity_id: sensor.living_room_thermostat_butterfly_hvac_state
      from: 'heating'
      to: 'off'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.samsung_tv
          state: 'On'
        - condition: state
          entity_id: media_player._un65ju6700_un65ju6700
          state: 'on'
        - condition: state
          entity_id: sensor.chromecast
          state: 'On'
        - condition: state
          entity_id: media_player.pastarun
          state: 'on'
  action:
    - service: script.volume_decrease
      
