- alias: "House Were home"
  trigger:
    - platform: state
      entity_id: climate.living_room_butterfly.attributes["away_mode"]
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: switch.turn_on
    entity_id: switch.corner_light