# Automations

###############
# Turn on corner light when nest switches from 
# away to home mode only when sun is down
- alias: We are home
  trigger:
    - platform: state
      entity_id: sensor.nest_away_mode
      state: 'False'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: switch.turn_on
      entity_id: switch.corner_light

###############
# Turn off firelight when corner light is turned on after 1min
- alias: Turn off firelight
  trigger: 
    - platform: state
      entity_id: switch.corner_light
      state: 'on'
      for: '00:01:00'
  condition:
    - condition: state
      entity_id: light.hall_light
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.hall_light

###############
# Send a push notification when login failure is logged
- alias: Login Failure
  hide_entity: true
  trigger:
    platform: template
    value_template: "{{ states('persistent_notification.httplogin') != 'unknown' }}"
  action:
    service: notify.rdpi
    data:
      title: 'Bad Login'
      message: There was a Hack attempt! Go Check Hass GUI for details.

###############
# Notify when fan is on under away settings
- alias: Away Fan On
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_thermostat_butterfly_fan
      state: 'on'
  condition:
    - condition: state
      entity_id: sensor.nest_away_mode
      state: 'True'
  action:
    - service: notify.rdpi
      data:
        title: 'Nest Mode'
        message: 'Fan ON under away mode'