# Automations
###############

###############
# Send motion detection notification if nest is set to eco under safe mode
- alias: Detect Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_thermostat_butterfly_has_leaf
      from: 'on'
  condition:
    - condition: state
      entity_id: sensor.away_mode
      state: 'on'
  action:
    - service: notify.rdpi
      data:
        title: 'Automation'
        message: Motion detected


###############
# Turn on corner light when nest switches from 
# away to home mode only when sun is down
- alias: Away mode turned off
  trigger:
    - platform: state
      entity_id: sensor.away_mode
      from: 'on'
  action:
    - service_template: >
        {%- if is_state("sun.sun", "below_horizon") -%}
          switch.turn_on
        {%- else -%}
          switch.turn_off
        {%- endif -%}
      entity_id: switch.corner_light
    - service: notify.rdpi
      data:
        title: 'Automation'
        message: Turn on light with door open

###############
# Turn off firelight when corner light is turned on after 1min
- alias: Turn off firelight
  trigger: 
    - platform: state
      entity_id: switch.corner_light
      state: 'on'
      for: '00:01:00'
  condition:
    - condition: state
      entity_id: light.hall_light
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.hall_light


###############
# Send a push notification when login failure is logged
- alias: Login Failure
  hide_entity: true
  trigger:
    platform: template
    value_template: "{{ states('persistent_notification.httplogin') != 'unknown' }}"
  action:
    service: notify.rdpi
    data:
      title: 'Bad Login'
      message: There was a Hack attempt! Go Check HA GUI for details.


###############
# Notify when fan is on under away settings
# testing
- alias: Away Fan On
  trigger:
    - platform: state
      entity_id: sensor.living_room_thermostat_butterfly_hvac_state
      from: 'off'
  condition:
    - condition: state
      entity_id: sensor.away_mode
      state: 'on'
  action:
    - service: notify.rdpi
      data:
        title: 'Nest Mode'
        message: 'Fan ON under away mode'
#    - alias: Nest to away
#      service: climate.set_away_mode
 #     data:
  #      entity_id: climate.living_room_butterfly
   #     away_mode: true
    

###############
# Increase TV volume when aircon on
- alias: Increase TV volume
  trigger:
    - platform: state
      entity_id: sensor.living_room_thermostat_butterfly_hvac_state
      from: 'off'
  condition:
    - condition: state
      entity_id: sensor.tv_status
      state: 'on'
  action:
    - service: script.volume_increase


###############
# Decrease TV volume when aircon off
- alias: Decrease TV volume
  trigger:
    - platform: state
      entity_id: sensor.living_room_thermostat_butterfly_hvac_state
      to: 'off'
  condition:
    - condition: state
      entity_id: sensor.tv_status
      state: 'on'
  action:
    - service: script.volume_decrease

###############
# Turn on light 50mins before sunset
- alias: Sun-down window lights
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:50:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.away_mode
        state: 'off'
      - condition: state
        entity_id: switch.corner_light
        state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.hall_light
      data:
        brightness: 180
    - service: notify.rdpi
      data:
        title: 'Lights'
        message: Sun-down lights automation