##################################
## StateAttribute Sensors
##################################
- platform: template
  sensors:
    nest_away_mode:
      friendly_name: 'Nest Away Mode'
      sensor_class: motion
      value_template: >-
        {%- if is_state_attr('climate.living_room_butterfly', 'away_mode', 'on')
          and is_state("binary_sensor.living_room_thermostat_butterfly_has_leaf", "on")
          and is_state("sensor.living_room_thermostat_butterfly_operation_mode", "eco")
          and is_state("sensor.living_room_thermostat_butterfly_hvac_state", "off") -%}
        on
        {%- else -%}
        off
        {%- endif -%}
      entity_id:
        - sensor.living_room_thermostat_butterfly_operation_mode
        - sensor.living_room_thermostat_butterfly_hvac_state
        - climate.living_room_butterfly
        - binary_sensor.living_room_thermostat_butterfly_has_leaf        
    
    tv_status:
      friendly_name: 'TV Status'
      value_template: >-
        {%- if is_state("sensor.samsung_tv", "On")
          and is_state("sensor.chromecast", "On")
          and (is_state("media_player._un65ju6700_un65ju6700", "on")
          or is_state("media_player._un65ju6700_un65ju6700", "off")
          or is_state("media_player.pastarun", "on")
          or is_state("media_player.pastarun", "off")) -%}
        on     
        {%- else -%}
        off
        {%- endif -%}
      entity_id:
        - sensor.samsung_tv
        - sensor.chromecast
        - media_player.pastarun
        - media_player._un65ju6700_un65ju6700
        - sensor.living_room_thermostat_butterfly_hvac_state
        
    away_mode:
      friendly_name: "Away Status"
      value_template: >-
        {%- if is_state("binary_sensor.nest_away_mode", "on")
          and is_state("device_tracker.rahul_ph", "not_home")
          and is_state("device_tracker.divya_ph", "not_home")
          and is_state("device_tracker.ipad_rahul", "not_home")
          and is_state("device_tracker.ipad_divya", "not_home")
          and is_state("device_tracker.macbook_pro", "not_home")
          and is_state("binary_sensor.tv_status", "off") -%}
        on
        {%- else -%}
        off
        {%- endif -%}
      entity_id:
        - binary_sensor.nest_away_mode
        - sensor.living_room_thermostat_butterfly_hvac_state
        - device_tracker.rahul_ph
        - device_tracker.divya_ph
        - device_tracker.ipad_rahul
        - device_tracker.ipad_divya
        - device_tracker.macbook_pro
        - binary_sensor.tv_status
