##################################
## StateAttribute Sensors
##################################
- platform: template
  sensors:
    nest_away_mode:
      friendly_name: 'Nest Away Mode'
      value_template: "{{ is_state_attr('climate.living_room_butterfly', 'away_mode', 'on') }}"
      sensor_class: motion
      entity_id:
        - sensor.living_room_thermostat_butterfly_operation_mode
        - sensor.living_room_thermostat_butterfly_hvac_state
        
    