##################################
## StateAttribute Sensors
##################################
- platform: template
  sensors:
    nest_away_mode:
      friendly_name: 'Nest Away Mode'
      value_template: "{{ is_state_attr('climate.living_room_butterfly', 'away_mode', 'on') }}"
      sensor_class: motion
      entity_id:
        - sensor.living_room_thermostat_butterfly_operation_mode
        - sensor.living_room_thermostat_butterfly_hvac_state
        - device_tracker.rahul_ph
        - device_tracker.divya_ph
        - binary_sensor.living_room_thermostat_butterfly_has_leaf        
    
    tv_status:
      friendly_name: 'TV Status'
      value_template: >-
        {%- if is_state("sensor.samsung_tv", "On")
          and is_state("media_player._un65ju6700_un65ju6700", "on")
          and is_state("sensor.chromecast", "On")
          and is_state("media_player.pastarun", "on") -%}
        on
        {%- else -%}
        off
        {%- endif -%}
      entity_id:
        - sensor.samsung_tv
        - sensor.chromecast
        - media_player.pastarun
        - media_player._un65ju6700_un65ju6700
        
#    away_mode:
 #     friendly_name: "Away Status"
  #    value_template: >-
   #     {%- if is_state("