##################################
## WEATHER & Date
##################################
- platform: yr

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'beat'
    
##################################
## Device Tracker Sensors
##################################
- platform: template
  sensors:
    samsung_tv:
      friendly_name: 'Samsung TV'
      value_template: "{{ 'On' if is_state('device_tracker.samsung_tv','home') else 'Off' }}"
    
    chromecast:
      friendly_name: 'ChromeCast Pastarun'
      value_template: "{{ 'On' if is_state('device_tracker.chromecast', 'home') else 'Off' }}"


##################################
## System Monitor
##################################
- platform: systemmonitor
  resources:
    - type: since_last_boot
    - type: disk_use_percent
      arg: /home
    - type: memory_use_percent
    - type: processor_use

- platform: template
  sensors:
    since_last_boot_templated:
      value_template: >-
        {%- set slb = states.sensor.since_last_boot.state.split(' ') -%}
        {%- set count = slb | length -%}
        {%- set hms = slb[count - 1] -%}
        {%- set hms_trimmed = hms.split('.')[0] -%}
        {%- set hms_split = hms_trimmed.split(':') -%}
        {%- set hours = hms_split[0] | int -%}
        {%- set minutes = hms_split[1] | int -%}
        {%- set seconds = hms_split[2] | int -%}
        {%- if count == 3 -%}
          {{ slb[0] ~ ' ' ~ slb[1] ~ ' ' }}
        {%- endif -%}
        {%- if hours > 0 -%}
          {%- if hours == 1 -%}
            1 hr
          {%- else -%}
            {{ hours }} hr
          {%- endif -%}
        {%- endif -%}
        {%- if minutes > 0 -%}
          {%- if hours > 0 -%}
            {{ ', ' }}
          {%- endif -%}
          {%- if minutes == 1 -%}
            1 min
          {%- else -%}
            {{ minutes }} min
          {%- endif -%}
        {%- endif -%}


##################################
## TV status
##################################
- platform: template
  sensors:
    tv_status:
      friendly_name: 'TV Status'
      value_template: >-
        {%- if is_state("sensor.samsung_tv", "On")
        and is_state("sensor.chromecast", "On")
        and (is_state("media_player._un65ju6700_un65ju6700", "on")
        or is_state("media_player._un65ju6700_un65ju6700", "off")
        or is_state("media_player.pastarun", "on")
        or is_state("media_player.pastarun", "off")) -%}
          on
        {%- else -%}
          off
        {%- endif -%}
      entity_id:
        - sensor.samsung_tv
        - sensor.chromecast
        - media_player.pastarun
        - media_player._un65ju6700_un65ju6700
        - sensor.living_room_thermostat_butterfly_hvac_state

##################################
## Away Status
##################################
- platform: template
  sensors:
    away_mode:
      friendly_name: "Away Status"
      value_template: >-
        {%- if is_state("binary_sensor.nest_away_mode", "on")
        and is_state("device_tracker.rahul_ph", "not_home")
        and is_state("device_tracker.divya_ph", "not_home")
        and is_state("device_tracker.ipad_rahul", "not_home")
        and is_state("device_tracker.ipad_divya", "not_home")
        and is_state("device_tracker.macbook_pro", "not_home")
        and is_state("binary_sensor.tv_status", "off") -%}
          on
        {%- else -%}
          off
        {%- endif -%}
      entity_id:
        - binary_sensor.nest_away_mode
        - sensor.living_room_thermostat_butterfly_hvac_state
        - device_tracker.rahul_ph
        - device_tracker.divya_ph
        - device_tracker.ipad_rahul
        - device_tracker.ipad_divya
        - device_tracker.macbook_pro
        - binary_sensor.tv_status

##################################
## Nest Away
##################################
- platform: template
  sensors:
    nest_away_mode:
      friendly_name: 'Nest Away Mode'
      value_template: >-
        {%- if is_state_attr("climate.living_room_butterfly", "away_mode", "on")
        and is_state("binary_sensor.living_room_thermostat_butterfly_has_leaf", "on")
        and is_state("sensor.living_room_thermostat_butterfly_operation_mode", "eco")
        and is_state("sensor.living_room_thermostat_butterfly_hvac_state", "off") -%}
          on
        {%- else -%}
          off
        {%- endif -%}
      entity_id:
        - sensor.living_room_thermostat_butterfly_operation_mode
        - sensor.living_room_thermostat_butterfly_hvac_state
        - climate.living_room_butterfly
        - binary_sensor.living_room_thermostat_butterfly_has_leaf        
