- platform: template
  sensors:
     nest_away_mode:
       friendly_name: 'Nest Away Mode'
       entity_id: climate.living_room_butterfly
       value_template: "{{ is_state_attr('climate.living_room_butterfly', 'away_mode', 'on') }}"
     
     #samsung_tv:
      # friendly_name: 'Samsung TV'
      # value_template: "{{ 'On' if is_state('device_tracker.samsung_tv','home') else 'Off' }}""
      
- platform: yr

#- platform: time_date
#  display_options:
#    - 'time'
#    - 'date'

#- platform: systemmonitor
#  resources:
#    # - type: last_boot
#    - type: since_last_boot

#- platform: rest
#  resource: http://ip.jsontest.com
#  name: External IP
#  value_template: '{{ value_json.ip }}' 
