- platform: template
  sensors:
     nest_away_mode:
       friendly_name: 'Nest Away Mode'
       entity_id: climate.living_room_butterfly
       value_template: "{{ is_state_attr('climate.living_room_butterfly', 'away_mode', 'on') }}"

- platform: yr