##################################
## Broadlink switches
##################################
- platform: broadlink
  host: 192.168.1.146
  mac: 'B4:43:0D:EE:F4:FE'
  switches:
    sound_bar:
      command_on: 'JgAyAU4UKBMUEyYVFBMmFRMUExQTFBQTFBQTFCcUJhQUExMAAs1NFScUExQnExMUJxQUExMVEhUTFBQTExQnFCYVExQTAALMThQmFRQTJxQTFCYVExQUExMUExQUExMVJhQnFBQTEwACzE4VJxMTFCgUExMoExQTFBMUFBMUExQTFCYVJhUTFBMAAsxOFCYVExQnFBIVJhQTFRMUEhUTFBMUExUmFCcUExQUAALLThQnFBQTJhUTFCYVExQTFBMUExQTFRIVJhQoExQTEwACzE8TKBMUFCYUExQnFBMUExQUExQUEhUTFCYVJxMUFBIAAs1OFCcUEhUnFBMUJxQSFRIVExQTFBQTFBMoEygTExQTAALMThQnFBMUJxQTFCYVFBMTFBMVEhUTFBMUJxQmFBQUEwANBQAAAAAAAA=='
      command_off: 'JgCqAE0VJxQTFCYVEhUmFRMUEhUTFBMUFBMTFCcUJxQTFBQAAstPEyYVExQmFRMUJhUTFBMUExQUFBIUFBQnEycUExQTAALMTxMnFBQTJxQUEycUEhUTFBMUExQTFRIVJxQmFRIVEgACzE8UJhQUEycUExQnFBQUEhQUFBMUExQTFCYVJhUSFRIAAs1NFScUExQnExMVJhUTFBMUExQUExMUExUnEygTExQUAA0FAAAAAAAAAAAAAAAAAAA='
      friendly_name: 'Sound Power'
    
    tv_curve:
      command_on: 'JgDSAJKUEzYSNxI3EhMSExITEhIUEhI3EjcTNhMSEhIUERMSExISExM2EhMTEhITExISExMSEzYSExM2EzYSNxI3EzYTNhIABfWTkxM2EjcTNhMSEhMSExITExISNxM2EjcTEhITEhMTEhITExISNxITEhMTEhITEhMTEhI3ExISNxI3EzYTNhM2EjcTAAX0k5IUNRQ2EzYTEhITEhITEhQSETcTNhM3EhMSEhMSEhMTExETEzYTEhMSExITEhITEhMSNxITEzYSNxI3EzYTNhI3EwANBQAAAAAAAA=='
      command_off: 'JgDSAJOTEzYSNxI3EhMSExMSEhMTEhM2EzYSNxITExITEhMREhMTEhI3ExISExMSExISExITEzYTEhM2EjcTNhM2EzYTNhMABfSSlBM2EzYSNxMSEhMSExMSEhMTNhM2EjcSExITExISExITEhMSNxITExISExMSEhMTEhI3EhMTNhM2EzYTNhM2EjcSAAX1kpQTNhM2EjcSExMSEhMTEhMSEjcTNhM2ExISExITEhMSExMSEjcSExMSEhITExITEhITNhQREzYSOBI3EzYSNxM2EwANBQAAAAAAAA=='
      friendly_name: 'TV Power'
    
    volume_media:
      command_on: 'JgCqAE8SFBMnFBMVExUmFBMUExURFhIVERYSFCcVJBcSFhEAAuBNFhMUJBYSFRIWJRYSFRIVEhQTFBQVEBcnEycUFRISAALgTRYSFiUVEhUTEycVEhQTFRQTExQSFhEWJhQmFhEVEgAC4U0VERUnFRQTEhUmFRIVEhUSFhEYDxcPFyYVJhQUFBIAAuFLFhMVJRURFhIbIRcPGg0WEhYSFBMWEhMnFiUTExYSAA0FAAAAAAAAAAAAAAAAAAA='
      command_off: 'JgDMAE4UJRYmFBYSEhUmFBQUEhYQFxQSExUTEycVJhUSFRMAAstOFCcUJhUTFRIVJRUUFBIVERYSFREXERUoEycUFhESAALNTRUnEycVEhQTFCcUExQTFREWExQTFBMVJRUmFRIVEwACzE0VJxQnFBIVEhUnExMWEhQSFhIUExQTFSYUJxQTFRIAAsxOFScUJRYSFBMVJhQTFBMUExUSExQVExQlFiYVExURAALNTRYlFiYTExUSFSUWEhUTFBMUFBQSFBMVJxMoExMVEgANBQAAAAAAAAAAAAAAAA=='
      friendly_name: 'Volume Control'