##################################
## Broadlink switches
##################################
- platform: broadlink
  host: 192.168.1.146
  mac: 'B4:43:0D:EE:F4:FE'
  switches:
    sound_bar:
      command_on: 'JgDuAE4VJhQTFCYVExQnFBIWEhUSFRMUEhUTFCYVJxQTFBMAAsxOFCcTExUnExMUKBMUExMVEhUSFRMUExQoEyYVEhUUAALLTRUnFBEWJxMUFCYVExQSFRIVExQTFBQTJxQmFRMUEwACzE0VJhQTFScTExQnFBQUERYTFBMUExQTFCcUJhUUExMAAsxOFCcTExUmFRMUJhQTFRMUFBMTFBMVEhQoEycUFBMTAALMTxMmFRQTJxQTFCYVExQTFBQTExQTFBQUJhQnFBQTEwACzE4UJxQTFCgTExQmFRQTExQSFRQUExQTFCYVJhQTFRMADQUAAAAAAAAAAAAA'
      command_off: 'JgCqAE4UJhUTFCYVExQmFRIVExQTFBMUFBMTFSYUKBMTFBMAAsxPEycUExQoExMUJxQTFBMUExQTFRIVExQmFSYUExUSAALNThQmFBMUJxQTFCcUExQTFBMVEhUTFBMUJxQmFRIVEgACzU0VJxMTFCcUExQoExMUExQTFRIVExQTFCYVJxQSFRIAAs1NFScTExQnFBMUJxQTFBMVExQSFRMUExQnFCYVEhUTAA0FAAAAAAAAAAAAAAAAAAA='
      friendly_name: 'Sound Power'
    
    tv_curve:
      command_on: 'JgCMAJWRFDUVNBU0FRAVEBUQFBEUERQ1FDUUNRQRFBEUERQQExIVEBM2FRAVEBUQFRAVEBUQFTQVEBU0FTQVNBI3FTQVNBUABfKVkRU0FTQVNBUQFRASExUQFRAVNBU0EjcVEBITFRAVEBUQFRAVNBMSEhMSExQRFBEUERQ1FBEUNRQ1FDUUNRQ1EjcVAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJKUEjcTNhM2EhMSExITFRATEhI3EjcSNxITEhMTEhITEhMUEBM2ExITEhMSEhMSExITEjcTEhI3EzYTNhU0EzYSNxMABfSSlBM2EzYVNBUQEhMTEhUQFRAVNBU0FTQSExITFRASExITFRAVNBMSFRASExUQFRAUERI3EhMSNxM2FTQVNBU0EjcSAA0FAAAAAAAAAAAAAAAA'
      friendly_name: 'TV Power'
    
    volume_media:
      command_on: 'JgCqAE8TFRIoExUSFRIoExUSFRIVEhUTFBMVEigTKBIVExQAAt5QEhUTKBIVEhUTKBIVExQTFBMVEhUSFRIpEigTFRIVAALdUBMUEygTFBMVEigTFBMVEhUSFRMUExQTKBMoEhUTFAAC3lASFRIpEhUSFRMoEhUTFBMUExQTFRIVEikSKBMUExUAAt5PExUSKBMVEhUSKBMVEhUSFRMUExQTFRIoEygTFBMUAA0FAAAAAAAAAAAAAAAAAAA='
      command_off: 'JgDMAE8TJxQnFBMUExQnFBMUFBMUExQTFBQTFCcTKBMUExQAAstPFCcTKBMUExQTKBMUExQTFBQTFBQTFBMnFCcUExQTAALMThQnFCcTFBQTFCcUExQTFBQTFBMUExQUJxMoExQTFAACy08TKBMnFBMUFBMnFBMUFBMUExQUExQTFCcUJxMUFBMAAstPFCcTKBMUExQTKBMUExQUExQTFBQTFBMnFCcUExQUAALLTRUnFCcUExQTFCcUExQTFBQTFBMUFBMUJhQnFBQTEwANBQAAAAAAAAAAAAAAAA=='
      friendly_name: 'Volume Control'
