homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include bin/customize.yaml
  
# introduction:
frontend:
http:
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: !secret base_url

updater:
discovery:
conversation:
history:
logbook:
sun:

tts:
  platform: google
  cache: false

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_uid
  password: !secret mqtt_pwd

## Start of devices
light:
  platform: lifx
  broadcast: 192.168.1.255

ifttt:
  key: !secret ifttt_key

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_key

climate:
  platform: nest

wemo:

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.100-150
    track_new_devices: no

notify:
  platform: pushbullet
  name: !secret pushname
  api_key: !secret pushbullet

switch:
  platform: broadlink
  host: 192.168.1.146
  mac: 'B4:43:0D:EE:F4:FE'
  switches:
    sound_bar:
      command_on: 'JgDuAE4VJhQTFCYVExQnFBIWEhUSFRMUEhUTFCYVJxQTFBMAAsxOFCcTExUnExMUKBMUExMVEhUSFRMUExQoEyYVEhUUAALLTRUnFBEWJxMUFCYVExQSFRIVExQTFBQTJxQmFRMUEwACzE0VJhQTFScTExQnFBQUERYTFBMUExQTFCcUJhUUExMAAsxOFCcTExUmFRMUJhQTFRMUFBMTFBMVEhQoEycUFBMTAALMTxMmFRQTJxQTFCYVExQTFBQTExQTFBQUJhQnFBQTEwACzE4UJxQTFCgTExQmFRQTExQSFRQUExQTFCYVJhQTFRMADQUAAAAAAAAAAAAA'
      command_off: 'JgCqAE4UJhUTFCYVExQmFRIVExQTFBMUFBMTFSYUKBMTFBMAAsxPEycUExQoExMUJxQTFBMUExQTFRIVExQmFSYUExUSAALNThQmFBMUJxQTFCcUExQTFBMVEhUTFBMUJxQmFRIVEgACzU0VJxMTFCcUExQoExMUExQTFRIVExQTFCYVJxQSFRIAAs1NFScTExQnFBMUJxQTFBMVExQSFRMUExQnFCYVEhUTAA0FAAAAAAAAAAAAAAAAAAA='
      friendly_name: 'Sound Power'
    tv_curve:
      command_on: 'JgCMAJKUEjcTNhM2ExISExMSExISExI3EjUUNxITEhMSExMSExISExI3ExISExMSEhMSExITEjcTEhI3EzYTNhM2EzYSNxMABfSSlBI3EzYSNxMSExITEhITExITNhM2EzYTEhMSEhMTEhITEhMSNxMSExITEhITEhITExI2ExITNhczEjcTNhI3EzYTAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJOTEjcTNhM3EhITEhMSExISExM2EzYTNhMSExISExITExISExI3EhMSExITEhMTEhITEzYSExM2EjcTNhI3EjcTNhMABfSTkxI3EjcSNxITEhMSExITEhMSNxI3EjcSExMSEhMSExMSEhMSNxMSExISExITExISExI3ExITNhI3EzYTNhM2EjcSAA0FAAAAAAAAAAAAAAAA'
      friendly_name: 'TV Power'
    volume_media:
      command_on: 'JgCqAE8TFRIoExUSFRIoExUSFRIVEhUTFBMVEigTKBIVExQAAt5QEhUTKBIVEhUTKBIVExQTFBMVEhUSFRIpEigTFRIVAALdUBMUEygTFBMVEigTFBMVEhUSFRMUExQTKBMoEhUTFAAC3lASFRIpEhUSFRMoEhUTFBMUExQTFRIVEikSKBMUExUAAt5PExUSKBMVEhUSKBMVEhUSFRMUExQTFRIoEygTFBMUAA0FAAAAAAAAAAAAAAAAAAA='
      command_off: 'JgDMAE8TJxQnFBMUExQnFBMUFBMUExQTFBQTFCcTKBMUExQAAstPFCcTKBMUExQTKBMUExQTFBQTFBQTFBMnFCcUExQTAALMThQnFCcTFBQTFCcUExQTFBQTFBMUExQUJxMoExQTFAACy08TKBMnFBMUFBMnFBMUFBMUExQUExQTFCcUJxMUFBMAAstPFCcTKBMUExQTKBMUExQUExQTFBQTFBMnFCcUExQUAALLTRUnFCcUExQTFCcUExQTFBQTFBMUFBMUJhQnFBQTEwANBQAAAAAAAAAAAAAAAA=='
      friendly_name: 'Volume Control'
      
#emulated_hue:
#  host_ip: !secret hostipaddress
#  type: google_home
#  listen_port: 80
#  expose_by_default: false

## include files
group: !include bin/group.yaml
script: !include bin/scripts.yaml
sensor: !include bin/sensors.yaml
automation: !include bin/automations.yaml
