homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  
# introduction:


frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google
  cache: false

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: pi
  password: raspberry

## Start of devices

# LIFX
light:
  platform: lifx
  broadcast: 192.168.1.255

ifttt:
  key: !secret ifttt_key

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_key

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.100-150
    track_new_devices: no

notify:
  platform: pushbullet
  name: RDPI
  api_key: !secret pushbullet

## include files
group: !include bin/group.yaml
script: !include bin/scripts.yaml

